---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aachen-transparent

resources:
- namespace.yaml
- elasticsearch.yaml
- objectstore-claims.yaml
- objectstore-service.yaml
# - objectstore-user.yaml # does not belong into aachen-transparent namespace!
- backend-service.yaml
- backend-deployment.yaml
- static-service.yaml
- static-deployment.yaml
- ingress.yaml
# - worker-deployment.yaml # not ready yet

secretGenerator:
- name: demo-auth
  files:
  - files/auth
- name: config
  envs:
  - files/env.txt
  type: Opaque

images:
- name: meine-stadt-transparent
  newName: ghcr.io/odlabac/aachen-transparent

generatorOptions:
  disableNameSuffixHash: true
